// Code generated by github.com/efritz/go-mockgen 0.1.0; DO NOT EDIT.

package protomock

import (
	"context"
	proto "github.com/aphistic/softcopy/pkg/proto"
	grpc "google.golang.org/grpc"
	"sync"
)

// MockSoftcopyAdminClient is a mock implementation of the
// SoftcopyAdminClient interface (from the package
// github.com/aphistic/softcopy/pkg/proto) used for unit testing.
type MockSoftcopyAdminClient struct {
	// AllFilesFunc is an instance of a mock function object controlling the
	// behavior of the method AllFiles.
	AllFilesFunc *SoftcopyAdminClientAllFilesFunc
}

// NewMockSoftcopyAdminClient creates a new mock of the SoftcopyAdminClient
// interface. All methods return zero values for all results, unless
// overwritten.
func NewMockSoftcopyAdminClient() *MockSoftcopyAdminClient {
	return &MockSoftcopyAdminClient{
		AllFilesFunc: &SoftcopyAdminClientAllFilesFunc{
			defaultHook: func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error) {
				return nil, nil
			},
		},
	}
}

// NewMockSoftcopyAdminClientFrom creates a new mock of the
// MockSoftcopyAdminClient interface. All methods delegate to the given
// implementation, unless overwritten.
func NewMockSoftcopyAdminClientFrom(i proto.SoftcopyAdminClient) *MockSoftcopyAdminClient {
	return &MockSoftcopyAdminClient{
		AllFilesFunc: &SoftcopyAdminClientAllFilesFunc{
			defaultHook: i.AllFiles,
		},
	}
}

// SoftcopyAdminClientAllFilesFunc describes the behavior when the AllFiles
// method of the parent MockSoftcopyAdminClient instance is invoked.
type SoftcopyAdminClientAllFilesFunc struct {
	defaultHook func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error)
	hooks       []func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error)
	history     []SoftcopyAdminClientAllFilesFuncCall
	mutex       sync.Mutex
}

// AllFiles delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockSoftcopyAdminClient) AllFiles(v0 context.Context, v1 *proto.AllFileRequest, v2 ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error) {
	r0, r1 := m.AllFilesFunc.nextHook()(v0, v1, v2...)
	m.AllFilesFunc.appendCall(SoftcopyAdminClientAllFilesFuncCall{v0, v1, v2, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the AllFiles method of
// the parent MockSoftcopyAdminClient instance is invoked and the hook queue
// is empty.
func (f *SoftcopyAdminClientAllFilesFunc) SetDefaultHook(hook func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// AllFiles method of the parent MockSoftcopyAdminClient instance inovkes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *SoftcopyAdminClientAllFilesFunc) PushHook(hook func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *SoftcopyAdminClientAllFilesFunc) SetDefaultReturn(r0 proto.SoftcopyAdmin_AllFilesClient, r1 error) {
	f.SetDefaultHook(func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error) {
		return r0, r1
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *SoftcopyAdminClientAllFilesFunc) PushReturn(r0 proto.SoftcopyAdmin_AllFilesClient, r1 error) {
	f.PushHook(func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error) {
		return r0, r1
	})
}

func (f *SoftcopyAdminClientAllFilesFunc) nextHook() func(context.Context, *proto.AllFileRequest, ...grpc.CallOption) (proto.SoftcopyAdmin_AllFilesClient, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *SoftcopyAdminClientAllFilesFunc) appendCall(r0 SoftcopyAdminClientAllFilesFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of SoftcopyAdminClientAllFilesFuncCall objects
// describing the invocations of this function.
func (f *SoftcopyAdminClientAllFilesFunc) History() []SoftcopyAdminClientAllFilesFuncCall {
	f.mutex.Lock()
	history := make([]SoftcopyAdminClientAllFilesFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// SoftcopyAdminClientAllFilesFuncCall is an object that describes an
// invocation of method AllFiles on an instance of MockSoftcopyAdminClient.
type SoftcopyAdminClientAllFilesFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 *proto.AllFileRequest
	// Arg2 is a slice containing the values of the variadic arguments
	// passed to this method invocation.
	Arg2 []grpc.CallOption
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 proto.SoftcopyAdmin_AllFilesClient
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation. The variadic slice argument is flattened in this array such
// that one positional argument and three variadic arguments would result in
// a slice of four, not two.
func (c SoftcopyAdminClientAllFilesFuncCall) Args() []interface{} {
	trailing := []interface{}{}
	for _, val := range c.Arg2 {
		trailing = append(trailing, val)
	}

	return append([]interface{}{c.Arg0, c.Arg1}, trailing...)
}

// Results returns an interface slice containing the results of this
// invocation.
func (c SoftcopyAdminClientAllFilesFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}
