// Code generated by protoc-gen-go. DO NOT EDIT.
// source: softcopy.proto

package scproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash                 string               `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Filename             string               `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	DocumentDate         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=document_date,json=documentDate,proto3" json:"document_date,omitempty"`
	Size                 int64                `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetDocumentDate() *timestamp.Timestamp {
	if m != nil {
		return m.DocumentDate
	}
	return nil
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type TaggedFile struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaggedFile) Reset()         { *m = TaggedFile{} }
func (m *TaggedFile) String() string { return proto.CompactTextString(m) }
func (*TaggedFile) ProtoMessage()    {}
func (*TaggedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{1}
}
func (m *TaggedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaggedFile.Unmarshal(m, b)
}
func (m *TaggedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaggedFile.Marshal(b, m, deterministic)
}
func (dst *TaggedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaggedFile.Merge(dst, src)
}
func (m *TaggedFile) XXX_Size() int {
	return xxx_messageInfo_TaggedFile.Size(m)
}
func (m *TaggedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_TaggedFile.DiscardUnknown(m)
}

var xxx_messageInfo_TaggedFile proto.InternalMessageInfo

func (m *TaggedFile) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *TaggedFile) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	System               bool     `protobuf:"varint,4,opt,name=system,proto3" json:"system,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{2}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Tag) GetSystem() bool {
	if m != nil {
		return m.System
	}
	return false
}

type GetFileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{3}
}
func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(dst, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFileResponse struct {
	File                 *TaggedFile `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{4}
}
func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(dst, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFile() *TaggedFile {
	if m != nil {
		return m.File
	}
	return nil
}

type FindFilesWithTagsRequest struct {
	TagNames             []string `protobuf:"bytes,1,rep,name=tag_names,json=tagNames,proto3" json:"tag_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFilesWithTagsRequest) Reset()         { *m = FindFilesWithTagsRequest{} }
func (m *FindFilesWithTagsRequest) String() string { return proto.CompactTextString(m) }
func (*FindFilesWithTagsRequest) ProtoMessage()    {}
func (*FindFilesWithTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{5}
}
func (m *FindFilesWithTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilesWithTagsRequest.Unmarshal(m, b)
}
func (m *FindFilesWithTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilesWithTagsRequest.Marshal(b, m, deterministic)
}
func (dst *FindFilesWithTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilesWithTagsRequest.Merge(dst, src)
}
func (m *FindFilesWithTagsRequest) XXX_Size() int {
	return xxx_messageInfo_FindFilesWithTagsRequest.Size(m)
}
func (m *FindFilesWithTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilesWithTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilesWithTagsRequest proto.InternalMessageInfo

func (m *FindFilesWithTagsRequest) GetTagNames() []string {
	if m != nil {
		return m.TagNames
	}
	return nil
}

type FindFilesWithTagsResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFilesWithTagsResponse) Reset()         { *m = FindFilesWithTagsResponse{} }
func (m *FindFilesWithTagsResponse) String() string { return proto.CompactTextString(m) }
func (*FindFilesWithTagsResponse) ProtoMessage()    {}
func (*FindFilesWithTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{6}
}
func (m *FindFilesWithTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilesWithTagsResponse.Unmarshal(m, b)
}
func (m *FindFilesWithTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilesWithTagsResponse.Marshal(b, m, deterministic)
}
func (dst *FindFilesWithTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilesWithTagsResponse.Merge(dst, src)
}
func (m *FindFilesWithTagsResponse) XXX_Size() int {
	return xxx_messageInfo_FindFilesWithTagsResponse.Size(m)
}
func (m *FindFilesWithTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilesWithTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilesWithTagsResponse proto.InternalMessageInfo

func (m *FindFilesWithTagsResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type FindFilesWithIdPrefixRequest struct {
	IdPrefix             string   `protobuf:"bytes,1,opt,name=id_prefix,json=idPrefix,proto3" json:"id_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFilesWithIdPrefixRequest) Reset()         { *m = FindFilesWithIdPrefixRequest{} }
func (m *FindFilesWithIdPrefixRequest) String() string { return proto.CompactTextString(m) }
func (*FindFilesWithIdPrefixRequest) ProtoMessage()    {}
func (*FindFilesWithIdPrefixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{7}
}
func (m *FindFilesWithIdPrefixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilesWithIdPrefixRequest.Unmarshal(m, b)
}
func (m *FindFilesWithIdPrefixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilesWithIdPrefixRequest.Marshal(b, m, deterministic)
}
func (dst *FindFilesWithIdPrefixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilesWithIdPrefixRequest.Merge(dst, src)
}
func (m *FindFilesWithIdPrefixRequest) XXX_Size() int {
	return xxx_messageInfo_FindFilesWithIdPrefixRequest.Size(m)
}
func (m *FindFilesWithIdPrefixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilesWithIdPrefixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilesWithIdPrefixRequest proto.InternalMessageInfo

func (m *FindFilesWithIdPrefixRequest) GetIdPrefix() string {
	if m != nil {
		return m.IdPrefix
	}
	return ""
}

type FindFilesWithIdPrefixResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFilesWithIdPrefixResponse) Reset()         { *m = FindFilesWithIdPrefixResponse{} }
func (m *FindFilesWithIdPrefixResponse) String() string { return proto.CompactTextString(m) }
func (*FindFilesWithIdPrefixResponse) ProtoMessage()    {}
func (*FindFilesWithIdPrefixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_softcopy_5e9c0e77eed116c0, []int{8}
}
func (m *FindFilesWithIdPrefixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilesWithIdPrefixResponse.Unmarshal(m, b)
}
func (m *FindFilesWithIdPrefixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilesWithIdPrefixResponse.Marshal(b, m, deterministic)
}
func (dst *FindFilesWithIdPrefixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilesWithIdPrefixResponse.Merge(dst, src)
}
func (m *FindFilesWithIdPrefixResponse) XXX_Size() int {
	return xxx_messageInfo_FindFilesWithIdPrefixResponse.Size(m)
}
func (m *FindFilesWithIdPrefixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilesWithIdPrefixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilesWithIdPrefixResponse proto.InternalMessageInfo

func (m *FindFilesWithIdPrefixResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "scproto.File")
	proto.RegisterType((*TaggedFile)(nil), "scproto.TaggedFile")
	proto.RegisterType((*Tag)(nil), "scproto.Tag")
	proto.RegisterType((*GetFileRequest)(nil), "scproto.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "scproto.GetFileResponse")
	proto.RegisterType((*FindFilesWithTagsRequest)(nil), "scproto.FindFilesWithTagsRequest")
	proto.RegisterType((*FindFilesWithTagsResponse)(nil), "scproto.FindFilesWithTagsResponse")
	proto.RegisterType((*FindFilesWithIdPrefixRequest)(nil), "scproto.FindFilesWithIdPrefixRequest")
	proto.RegisterType((*FindFilesWithIdPrefixResponse)(nil), "scproto.FindFilesWithIdPrefixResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SoftcopyClient is the client API for Softcopy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SoftcopyClient interface {
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	FindFilesWithIdPrefix(ctx context.Context, in *FindFilesWithIdPrefixRequest, opts ...grpc.CallOption) (*FindFilesWithIdPrefixResponse, error)
	FindFilesWithTags(ctx context.Context, in *FindFilesWithTagsRequest, opts ...grpc.CallOption) (*FindFilesWithTagsResponse, error)
}

type softcopyClient struct {
	cc *grpc.ClientConn
}

func NewSoftcopyClient(cc *grpc.ClientConn) SoftcopyClient {
	return &softcopyClient{cc}
}

func (c *softcopyClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/scproto.Softcopy/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softcopyClient) FindFilesWithIdPrefix(ctx context.Context, in *FindFilesWithIdPrefixRequest, opts ...grpc.CallOption) (*FindFilesWithIdPrefixResponse, error) {
	out := new(FindFilesWithIdPrefixResponse)
	err := c.cc.Invoke(ctx, "/scproto.Softcopy/FindFilesWithIdPrefix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softcopyClient) FindFilesWithTags(ctx context.Context, in *FindFilesWithTagsRequest, opts ...grpc.CallOption) (*FindFilesWithTagsResponse, error) {
	out := new(FindFilesWithTagsResponse)
	err := c.cc.Invoke(ctx, "/scproto.Softcopy/FindFilesWithTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoftcopyServer is the server API for Softcopy service.
type SoftcopyServer interface {
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	FindFilesWithIdPrefix(context.Context, *FindFilesWithIdPrefixRequest) (*FindFilesWithIdPrefixResponse, error)
	FindFilesWithTags(context.Context, *FindFilesWithTagsRequest) (*FindFilesWithTagsResponse, error)
}

func RegisterSoftcopyServer(s *grpc.Server, srv SoftcopyServer) {
	s.RegisterService(&_Softcopy_serviceDesc, srv)
}

func _Softcopy_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftcopyServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scproto.Softcopy/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftcopyServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softcopy_FindFilesWithIdPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFilesWithIdPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftcopyServer).FindFilesWithIdPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scproto.Softcopy/FindFilesWithIdPrefix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftcopyServer).FindFilesWithIdPrefix(ctx, req.(*FindFilesWithIdPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softcopy_FindFilesWithTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFilesWithTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftcopyServer).FindFilesWithTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scproto.Softcopy/FindFilesWithTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftcopyServer).FindFilesWithTags(ctx, req.(*FindFilesWithTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Softcopy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scproto.Softcopy",
	HandlerType: (*SoftcopyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _Softcopy_GetFile_Handler,
		},
		{
			MethodName: "FindFilesWithIdPrefix",
			Handler:    _Softcopy_FindFilesWithIdPrefix_Handler,
		},
		{
			MethodName: "FindFilesWithTags",
			Handler:    _Softcopy_FindFilesWithTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "softcopy.proto",
}

func init() { proto.RegisterFile("softcopy.proto", fileDescriptor_softcopy_5e9c0e77eed116c0) }

var fileDescriptor_softcopy_5e9c0e77eed116c0 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0xc9, 0x9f, 0x6d, 0xd9, 0xdd, 0x56, 0x84, 0x11, 0x60, 0x02, 0x88, 0xcc, 0x08, 0xe8,
	0x53, 0x26, 0x95, 0x07, 0x24, 0x90, 0x80, 0x87, 0x69, 0x88, 0x17, 0x04, 0x21, 0x12, 0x2f, 0xa0,
	0xca, 0x6b, 0x5c, 0xd7, 0x52, 0x53, 0x87, 0xda, 0x95, 0x28, 0x1f, 0x83, 0x57, 0xbe, 0x2c, 0xca,
	0x8d, 0x13, 0xa5, 0xb4, 0x03, 0xf1, 0xe6, 0xeb, 0x7b, 0xae, 0xcf, 0xf9, 0xdd, 0x04, 0x06, 0x46,
	0x4f, 0xed, 0x44, 0x57, 0xeb, 0xb4, 0x5a, 0x6a, 0xab, 0xc9, 0x81, 0x99, 0xe0, 0x21, 0x7e, 0x28,
	0xb5, 0x96, 0x73, 0x71, 0x86, 0xd5, 0xe5, 0x6a, 0x7a, 0x66, 0x55, 0x29, 0x8c, 0xe5, 0x65, 0xd5,
	0x28, 0xd9, 0x2f, 0x0f, 0xc2, 0x0b, 0x35, 0x17, 0x64, 0x00, 0xbe, 0x2a, 0xa8, 0x97, 0x78, 0xc3,
	0xc3, 0xcc, 0x57, 0x05, 0x21, 0x10, 0xce, 0xb8, 0x99, 0x51, 0x1f, 0x6f, 0xf0, 0x4c, 0x62, 0x88,
	0xa6, 0x6a, 0x2e, 0x16, 0xbc, 0x14, 0x34, 0xc0, 0xfb, 0xae, 0x26, 0xaf, 0xe1, 0xa4, 0xd0, 0x93,
	0x55, 0x29, 0x16, 0x76, 0x5c, 0x70, 0x2b, 0x68, 0x98, 0x78, 0xc3, 0xa3, 0x51, 0x9c, 0x36, 0x09,
	0xd2, 0x36, 0x41, 0x9a, 0xb7, 0x09, 0xb2, 0xe3, 0x76, 0xe0, 0x9c, 0x5b, 0x51, 0x1b, 0x1a, 0xf5,
	0x43, 0xd0, 0xbd, 0xc4, 0x1b, 0x06, 0x19, 0x9e, 0xd9, 0x47, 0x80, 0x9c, 0x4b, 0x29, 0x0a, 0x8c,
	0x78, 0x0a, 0x61, 0x6d, 0x87, 0x21, 0x8f, 0x46, 0x27, 0xa9, 0x83, 0x4c, 0xeb, 0x66, 0x86, 0x2d,
	0x92, 0x40, 0x68, 0xb9, 0x34, 0xd4, 0x4f, 0x82, 0xe1, 0xd1, 0xe8, 0xb8, 0x93, 0xe4, 0x5c, 0x66,
	0xd8, 0x61, 0x5f, 0x21, 0xc8, 0xb9, 0xec, 0xe1, 0x06, 0x2d, 0x2e, 0x62, 0x39, 0x5c, 0x44, 0x8a,
	0x21, 0x9a, 0x70, 0x2b, 0xa4, 0x5e, 0xae, 0x5b, 0xdc, 0xb6, 0x26, 0xb7, 0x61, 0xdf, 0xac, 0x8d,
	0x15, 0x25, 0x72, 0x46, 0x99, 0xab, 0x58, 0x02, 0x83, 0xb7, 0xc2, 0x62, 0x22, 0xf1, 0x6d, 0x25,
	0x8c, 0xfd, 0x73, 0xb1, 0xec, 0x05, 0x5c, 0xef, 0x14, 0xa6, 0xd2, 0x0b, 0x23, 0xc8, 0xd3, 0x0d,
	0xb0, 0x9b, 0xfd, 0xd4, 0x8e, 0xbd, 0xc1, 0x63, 0xcf, 0x81, 0x5e, 0xa8, 0x05, 0xde, 0x98, 0xcf,
	0xca, 0xce, 0x72, 0x2e, 0x4d, 0xeb, 0x73, 0x0f, 0x0e, 0x2d, 0x97, 0xe3, 0x3a, 0xb9, 0xa1, 0x5e,
	0x12, 0xd4, 0x71, 0x2d, 0x97, 0xef, 0xeb, 0x9a, 0xbd, 0x81, 0xbb, 0x3b, 0x06, 0x9d, 0xfd, 0x23,
	0xd8, 0xab, 0x5f, 0x6f, 0xa6, 0xb6, 0x16, 0xdb, 0xf4, 0xd8, 0x4b, 0xb8, 0xbf, 0xf1, 0xc2, 0xbb,
	0xe2, 0xc3, 0x52, 0x4c, 0xd5, 0xf7, 0x9e, 0xbd, 0x2a, 0xc6, 0x15, 0xde, 0x39, 0xda, 0x48, 0x39,
	0x0d, 0x3b, 0x87, 0x07, 0x57, 0x0c, 0xff, 0x47, 0x84, 0xd1, 0x4f, 0x1f, 0xa2, 0x4f, 0xee, 0x47,
	0x27, 0xaf, 0xe0, 0xc0, 0xad, 0x91, 0xdc, 0xe9, 0xd4, 0x9b, 0xab, 0x8f, 0xe9, 0x76, 0xa3, 0xf1,
	0x63, 0xd7, 0xc8, 0x0c, 0x6e, 0xed, 0x8c, 0x44, 0x1e, 0xf7, 0xbc, 0xaf, 0xe6, 0x8d, 0x9f, 0xfc,
	0x4b, 0xd6, 0x39, 0x7d, 0x81, 0x1b, 0x5b, 0xbb, 0x27, 0xa7, 0xbb, 0xc7, 0x7b, 0x1f, 0x34, 0x66,
	0x7f, 0x93, 0xb4, 0xaf, 0x5f, 0xee, 0xa3, 0xe4, 0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae,
	0xa4, 0xa9, 0x02, 0x03, 0x04, 0x00, 0x00,
}
